version: '3.8'

services:
  backend:
    container_name: reusetechdev-backend
    build: ./backend
    restart: always
    network_mode: host
    env_file: ./backend/.env.dev
    volumes:
      - reusetech-data:/app/uploads

  ia_service:
    container_name: reusetechdev-ia
    build: ./ia_service/monitor_camara
    restart: always
    network_mode: host
    depends_on:
      - backend
    env_file: ./ia_service/monitor_camara/.env.dev
    volumes:
      - reusetech-data:/app/capturas

  frontend:
    container_name: reusetechdev-frontend
    build: ./frontend
    restart: always
    ports:
      - "3002:80"
    networks:
      - reusetech-net

networks:
  reusetech-net:
    driver: bridge

volumes:
  reusetech-data:
